services:
  - type: web
    name: frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    rootDir: frontend
    branch: main
    autoDeploy: true

  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=8080
    rootDir: backend
    branch: main
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11